language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install -g spago purescript
  - npm install
  - spago install
script:
  - npm run build
  - npm run example-icon:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: example/signal-halogen/dist
  on:
    branch: master
