language: node_js
dist: focal
sudo: required
node_js: stable
install:
  - npm install -g spago purescript
  - npm install
  - spago install
script:
  - npm run build
  - npm run examples-icon
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: examples/icon/dist
  on:
    branch: master
